{
  cross,
  homeManager,
  nixos,
  inputs,
  ...
}: {
  configurations.nixos.neko5.module = {
    imports = [
      nixos.nix
      nixos.nixStoreClean
      nixos.primaryUser
      nixos.homeManagerUser
      nixos.zsh
      nixos.time
      nixos.ssh
      nixos.locale
      nixos.systemState
      nixos.kernelLatest
      nixos.neko5Hardware
      nixos.unstablePackages
      nixos.llmAgents
      nixos.udiskie
      nixos.hyprlock
      nixos.openTabletDriver
      nixos.stubLd
      nixos.tailscale
      nixos.laptopInput
      nixos.systemdBoot
      nixos.networkManager
      nixos.pipewire
      nixos.bluetooth
      nixos.fonts
      nixos.intelGraphics
      nixos.desktopPerformance
      nixos.waylandSession
      nixos.fcitx5
      nixos.dolphin
      nixos.docker
      (cross.user "tenzyu" (
        (with cross.modules; [
          steam
          gaming
          android-mic
          discord
          prismlauncher
          codex
          opencode
          obsidian
          osu-lazer
          rtk
          catppuccin
          hyprland
        ])
        ++ (with homeManager; [
          common
          dolphin
          packagesCommon
          packagesDesktop
          zsh
          btop
          fastfetch
          firefox
          fzf
          git
          kitty
          neovim
          rofi
          starship
          tmux
          waybar
          mako
          wlogout
          yazi
          zedEditor
          zoxide
        ])
      ))
      ({pkgs, ...}: {
        home-manager.users."tenzyu".home.packages = with pkgs; [
          nh
          jq
          jqp
          lazygit
          zip
          ncdu
          crosspipe
          gh
          qdirstat
          inputs.castalia.packages.${pkgs.system}.castalia
          inputs.onair.packages.${pkgs.system}.default
        ];
      })
    ];
  };
}
